Smalltalk interchangeVersion: '1.0'!

Class named: 'OOBProxyData'
	superclass: 'Object'
	indexedInstanceVariables: #none
	instanceVariableNames: ''
	classVariableNames: ''
	sharedPools: ''
	classInstanceVariableNames: ''!
Annotation key: 'category' value: 'OOBench'!
Annotation key: 'comment' value: ''!
Annotation key: 'package' value: 'OOBench'!

OOBProxyData method!
theSize
	^1234.!
Annotation key: 'category' value: 'accessing'!

